# Generated by Django 4.1.5 on 2023-02-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='uuid',
            new_name='bookmark_uuid',
        ),
    ]
