# Generated by Django 4.1.5 on 2023-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_users_id_users_user_password_users_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
